### ISSUE TITLE
Adjustable keepalive interval and timeout

### ISSUE THREAD

**Issue by sQu1rr** [lowquark/uflow#1]
Would be great if the keepalive interval (currently 5 seconds) and timeout (currently 20 seconds) could be adjustable.

**Comment by lowquark** [comment]
Definitely! I have been working on a streamlined API (see the `dev` branch), and once that is released I try to add more configuration options. Adjustable window sizes also come to mind.

**Comment by lowquark** [comment]
Added to v0.7.1. I am curious, are there better default values that should be used instead?

Note: the handshake and disconnection timeouts are yet to be configurable, but I will try to implement this for v0.7.2 when I have the time.
